### ISSUE TITLE
Cloning this repo needs GitHub LFS

### ISSUE THREAD

**Issue by bokveizen** [young917/EdgeDependentNodeLabel#1]
Seemingly several files in this repo are stored with GitHub LFS (Large File Storage).
Hence, simply doing `git clone` may fail to download the whole repo.
Instead, we need `git lfs clone`.

Maybe you can put some instructions regarding LFS in readme.
See, e.g., [https://stackoverflow.com/questions/48734119](https://stackoverflow.com/questions/48734119).
See also [https://github.com/git-lfs/git-lfs/wiki/Installation](https://github.com/git-lfs/git-lfs/wiki/Installation).

It is possible that my Git version was too old though...

**Comment by young917** [comment]
Thank you!
